version: "3.3"

networks:
  public:
    driver: overlay
    attachable: true

services:
  portainer:
      image: portainer/portainer-ce:2.0.0
      command: -H unix:///var/run/docker.sock
      networks:
          - public 
      ports:
        - 9000:9000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      deploy:
        placement:
          constraints: [
            node.role == manager
          ]
        restart_policy:
          condition: any

volumes:
  portainer_data: